In [8]:
import pandas as pd
import numpy as np

The file `gapminder_with_missing.tsv` contains missing values indicated by `-1`

In [9]:
data = pd.read_csv('data/gapminder_with_missing.tsv', sep='\t')

In [10]:
data.head()

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083   -1.000000
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106

Calculate the average `lifeExp`, `pop`, and `gdpPercap`

In [11]:
data['lifeExp'].mean()

55.81203833333336

In [12]:
data['pop'].mean()

27992515.794014085

In [13]:
data['gdpPercap'].mean()

6833.852739445185

The values you calculated are not accurate because `-1` was included in the calculation. However, `-1` is used in the file to indicate the entry is missing. Let us deal with that.

Replace all `-1` with `NaN` *HINT* uses the function replace, i.e., `data.replace(...)`

In [14]:
data2 = data.replace(-1, np.nan)

Calculate the average `lifeExp`, `pop`, and `gdpPercap` again

In [15]:
data2['lifeExp'].mean()

59.391586600124796

In [16]:
data2['pop'].mean()

29774810.870786518

In [17]:
data2['gdpPercap'].mean()

7201.590641938526

In [19]:
pd.isnull(None)

True

What are the rows that contain missing values?

In [22]:
# solution 1: a (manual loop)
rm = set()
cm = set()
for i in data2.index:
    for c in data2.columns:
        if pd.isnull(data2.loc[i, c]):
            rm.add(i)
            cm.add(c)

In [23]:
rm

{2,
 7,
 29,
 32,
 39,
 42,
 45,
 58,
 61,
 68,
 69,
 73,
 79,
 83,
 101,
 102,
 104,
 113,
 114,
 127,
 129,
 145,
 147,
 154,
 158,
 159,
 161,
 169,
 173,
 178,
 179,
 185,
 189,
 190,
 192,
 196,
 197,
 200,
 209,
 210,
 224,
 226,
 240,
 243,
 245,
 253,
 259,
 261,
 268,
 276,
 283,
 286,
 293,
 297,
 309,
 320,
 321,
 328,
 338,
 340,
 342,
 354,
 358,
 374,
 380,
 391,
 401,
 410,
 416,
 424,
 430,
 431,
 433,
 438,
 448,
 452,
 470,
 475,
 480,
 492,
 495,
 498,
 501,
 502,
 503,
 524,
 525,
 549,
 550,
 554,
 557,
 574,
 581,
 585,
 587,
 606,
 609,
 631,
 632,
 638,
 644,
 645,
 647,
 650,
 658,
 663,
 665,
 667,
 674,
 680,
 691,
 697,
 711,
 721,
 723,
 727,
 741,
 754,
 762,
 790,
 793,
 799,
 800,
 802,
 804,
 809,
 811,
 821,
 825,
 832,
 838,
 845,
 847,
 853,
 863,
 867,
 868,
 874,
 875,
 880,
 881,
 882,
 889,
 892,
 902,
 903,
 904,
 920,
 947,
 958,
 982,
 983,
 984,
 987,
 994,
 998,
 1005,
 1014,
 1015,
 1017,
 1025,
 1047,
 1059,
 1070,
 1073,
 1081,
 1088,
 1099,
 1104,
 1106,
 1115,
 1117,
 1124,
 1127,
 1128,
 1138,
 1142,
 1151,
 1164,
 1165,
 1170,
 1179,
 1182,
 1195,
 1203,
 1212,
 1213,
 1230,
 1233,
 1235,
 1236,
 1238,
 1239,
 1240,
 1246,
 1247,
 1253,
 1257,
 1259,
 1261,
 1265,
 1271,
 1274,
 1277,
 1287,
 1294,
 1299,
 1306,
 1312,
 1317,
 1324,
 1325,
 1327,
 1328,
 1330,
 1334,
 1341,
 1347,
 1356,
 1360,
 1362,
 1364,
 1372,
 1374,
 1377,
 1383,
 1402,
 1408,
 1416,
 1417,
 1419,
 1420,
 1439,
 1441,
 1457,
 1466,
 1468,
 1474,
 1476,
 1483,
 1484,
 1492,
 1495,
 1499,
 1501,
 1508,
 1510,
 1511,
 1512,
 1521,
 1529,
 1533,
 1535,
 1539,
 1552,
 1553,
 1556,
 1558,
 1567,
 1568,
 1569,
 1570,
 1572,
 1578,
 1579,
 1611,
 1613,
 1629,
 1639,
 1648,
 1649,
 1655,
 1662,
 1663,
 1666,
 1673,
 1677,
 1689,
 1691}

In [24]:
cm

{'gdpPercap', 'lifeExp', 'pop'}

In [27]:
#solution 2: using index operation
set(
    data2.index.difference(data2.dropna().index)
    )

{2,
 7,
 29,
 32,
 39,
 42,
 45,
 58,
 61,
 68,
 69,
 73,
 79,
 83,
 101,
 102,
 104,
 113,
 114,
 127,
 129,
 145,
 147,
 154,
 158,
 159,
 161,
 169,
 173,
 178,
 179,
 185,
 189,
 190,
 192,
 196,
 197,
 200,
 209,
 210,
 224,
 226,
 240,
 243,
 245,
 253,
 259,
 261,
 268,
 276,
 283,
 286,
 293,
 297,
 309,
 320,
 321,
 328,
 338,
 340,
 342,
 354,
 358,
 374,
 380,
 391,
 401,
 410,
 416,
 424,
 430,
 431,
 433,
 438,
 448,
 452,
 470,
 475,
 480,
 492,
 495,
 498,
 501,
 502,
 503,
 524,
 525,
 549,
 550,
 554,
 557,
 574,
 581,
 585,
 587,
 606,
 609,
 631,
 632,
 638,
 644,
 645,
 647,
 650,
 658,
 663,
 665,
 667,
 674,
 680,
 691,
 697,
 711,
 721,
 723,
 727,
 741,
 754,
 762,
 790,
 793,
 799,
 800,
 802,
 804,
 809,
 811,
 821,
 825,
 832,
 838,
 845,
 847,
 853,
 863,
 867,
 868,
 874,
 875,
 880,
 881,
 882,
 889,
 892,
 902,
 903,
 904,
 920,
 947,
 958,
 982,
 983,
 984,
 987,
 994,
 998,
 1005,
 1014,
 1015,
 1017,
 1025,
 1047,
 1059,
 1070,
 1073,
 1081,
 1088,
 1099,
 1104,
 1106,
 1115,
 1117,
 1124,
 1127,
 1128,
 1138,
 1142,
 1151,
 1164,
 1165,
 1170,
 1179,
 1182,
 1195,
 1203,
 1212,
 1213,
 1230,
 1233,
 1235,
 1236,
 1238,
 1239,
 1240,
 1246,
 1247,
 1253,
 1257,
 1259,
 1261,
 1265,
 1271,
 1274,
 1277,
 1287,
 1294,
 1299,
 1306,
 1312,
 1317,
 1324,
 1325,
 1327,
 1328,
 1330,
 1334,
 1341,
 1347,
 1356,
 1360,
 1362,
 1364,
 1372,
 1374,
 1377,
 1383,
 1402,
 1408,
 1416,
 1417,
 1419,
 1420,
 1439,
 1441,
 1457,
 1466,
 1468,
 1474,
 1476,
 1483,
 1484,
 1492,
 1495,
 1499,
 1501,
 1508,
 1510,
 1511,
 1512,
 1521,
 1529,
 1533,
 1535,
 1539,
 1552,
 1553,
 1556,
 1558,
 1567,
 1568,
 1569,
 1570,
 1572,
 1578,
 1579,
 1611,
 1613,
 1629,
 1639,
 1648,
 1649,
 1655,
 1662,
 1663,
 1666,
 1673,
 1677,
 1689,
 1691}

In [29]:
set(
    data2.columns.difference(data2.dropna(axis=1).columns)
    )

{'gdpPercap', 'lifeExp', 'pop'}

In [ ]:
# solution 3: using masking

In [31]:
data2.isnull() # this gives us a boolean data frame

      country  continent   year  lifeExp    pop  gdpPercap
0       False      False  False    False  False      False
1       False      False  False    False  False      False
2       False      False  False    False  False       True
3       False      False  False    False  False      False
4       False      False  False    False  False      False
5       False      False  False    False  False      False
6       False      False  False    False  False      False
7       False      False  False     True  False      False
8       False      False  False    False  False      False
9       False      False  False    False  False      False
10      False      False  False    False  False      False
11      False      False  False    False  False      False
12      False      False  False    False  False      False
13      False      False  False    False  False      False
14      False      False  False    False  False      False
15      False      False  False    False  False      False
16      False      False  False    False  False      False
17      False      False  False    False  False      False
18      False      False  False    False  False      False
19      False      False  False    False  False      False
20      False      False  False    False  False      False
21      False      False  False    False  False      False
22      False      False  False    False  False      False
23      False      False  False    False  False      False
24      False      False  False    False  False      False
25      False      False  False    False  False      False
26      False      False  False    False  False      False
27      False      False  False    False  False      False
28      False      False  False    False  False      False
29      False      False  False    False   True      False
...       ...        ...    ...      ...    ...        ...
1674    False      False  False    False  False      False
1675    False      False  False    False  False      False
1676    False      False  False    False  False      False
1677    False      False  False    False   True      False
1678    False      False  False    False  False      False
1679    False      False  False    False  False      False
1680    False      False  False    False  False      False
1681    False      False  False    False  False      False
1682    False      False  False    False  False      False
1683    False      False  False    False  False      False
1684    False      False  False    False  False      False
1685    False      False  False    False  False      False
1686    False      False  False    False  False      False
1687    False      False  False    False  False      False
1688    False      False  False    False  False      False
1689    False      False  False     True  False       True
1690    False      False  False    False  False      False
1691    False      False  False     True  False      False
1692    False      False  False    False  False      False
1693    False      False  False    False  False      False
1694    False      False  False    False  False      False
1695    False      False  False    False  False      False
1696    False      False  False    False  False      False
1697    False      False  False    False  False      False
1698    False      False  False    False  False      False
1699    False      False  False    False  False      False
1700    False      False  False    False  False      False
1701    False      False  False    False  False      False
1702    False      False  False    False  False      False
1703    False      False  False    False  False      False

[1704 rows x 6 columns]

In [32]:
data2.isnull().any() #any function is used to create a mask
# if any row of a specific col is True, gives back True

country      False
continent    False
year         False
lifeExp       True
pop           True
gdpPercap     True
dtype: bool

In [36]:
#use masking
s = data2.isnull().any()
set(s[s].index)

{'gdpPercap', 'lifeExp', 'pop'}

In [38]:
#same as above but operate on the column axis,
#return True if any col of a specific row contains null
s = data2.isnull().any(axis=1)
set(s[s].index)

{2,
 7,
 29,
 32,
 39,
 42,
 45,
 58,
 61,
 68,
 69,
 73,
 79,
 83,
 101,
 102,
 104,
 113,
 114,
 127,
 129,
 145,
 147,
 154,
 158,
 159,
 161,
 169,
 173,
 178,
 179,
 185,
 189,
 190,
 192,
 196,
 197,
 200,
 209,
 210,
 224,
 226,
 240,
 243,
 245,
 253,
 259,
 261,
 268,
 276,
 283,
 286,
 293,
 297,
 309,
 320,
 321,
 328,
 338,
 340,
 342,
 354,
 358,
 374,
 380,
 391,
 401,
 410,
 416,
 424,
 430,
 431,
 433,
 438,
 448,
 452,
 470,
 475,
 480,
 492,
 495,
 498,
 501,
 502,
 503,
 524,
 525,
 549,
 550,
 554,
 557,
 574,
 581,
 585,
 587,
 606,
 609,
 631,
 632,
 638,
 644,
 645,
 647,
 650,
 658,
 663,
 665,
 667,
 674,
 680,
 691,
 697,
 711,
 721,
 723,
 727,
 741,
 754,
 762,
 790,
 793,
 799,
 800,
 802,
 804,
 809,
 811,
 821,
 825,
 832,
 838,
 845,
 847,
 853,
 863,
 867,
 868,
 874,
 875,
 880,
 881,
 882,
 889,
 892,
 902,
 903,
 904,
 920,
 947,
 958,
 982,
 983,
 984,
 987,
 994,
 998,
 1005,
 1014,
 1015,
 1017,
 1025,
 1047,
 1059,
 1070,
 1073,
 1081,
 1088,
 1099,
 1104,
 1106,
 1115,
 1117,
 1124,
 1127,
 1128,
 1138,
 1142,
 1151,
 1164,
 1165,
 1170,
 1179,
 1182,
 1195,
 1203,
 1212,
 1213,
 1230,
 1233,
 1235,
 1236,
 1238,
 1239,
 1240,
 1246,
 1247,
 1253,
 1257,
 1259,
 1261,
 1265,
 1271,
 1274,
 1277,
 1287,
 1294,
 1299,
 1306,
 1312,
 1317,
 1324,
 1325,
 1327,
 1328,
 1330,
 1334,
 1341,
 1347,
 1356,
 1360,
 1362,
 1364,
 1372,
 1374,
 1377,
 1383,
 1402,
 1408,
 1416,
 1417,
 1419,
 1420,
 1439,
 1441,
 1457,
 1466,
 1468,
 1474,
 1476,
 1483,
 1484,
 1492,
 1495,
 1499,
 1501,
 1508,
 1510,
 1511,
 1512,
 1521,
 1529,
 1533,
 1535,
 1539,
 1552,
 1553,
 1556,
 1558,
 1567,
 1568,
 1569,
 1570,
 1572,
 1578,
 1579,
 1611,
 1613,
 1629,
 1639,
 1648,
 1649,
 1655,
 1662,
 1663,
 1666,
 1673,
 1677,
 1689,
 1691}